-- =============================================================================
-- Supabase schema for: qr-id-login-supabase
-- =============================================================================
-- Run this in the Supabase Dashboard -> SQL Editor on a fresh project to
-- recreate everything the app needs (tables + indexes + storage bucket).
--
-- NOTE on security model:
--   The server (server.js) connects with the SERVICE ROLE key, which bypasses
--   Row Level Security (RLS). All access control is done in the Node backend,
--   not in the database. RLS is therefore disabled below by default. If you
--   ever expose these tables to the public ANON key, you MUST add RLS policies.
-- =============================================================================

-- Needed for gen_random_uuid()
create extension if not exists "pgcrypto";

-- -----------------------------------------------------------------------------
-- app_users: application accounts (custom auth, NOT Supabase Auth)
-- -----------------------------------------------------------------------------
create table if not exists public.app_users (
  id            uuid primary key default gen_random_uuid(),
  username      text not null unique,
  password_hash text not null,                 -- format: "saltHex:hashHex" (scrypt)
  created_at    timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- sessions: one-time upload sessions created when a QR code is generated
-- -----------------------------------------------------------------------------
create table if not exists public.sessions (
  id         uuid primary key,                 -- generated by the server (crypto.randomUUID)
  user_id    uuid not null references public.app_users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists sessions_user_id_idx on public.sessions(user_id);

-- -----------------------------------------------------------------------------
-- uploads: metadata for every image uploaded from a phone
-- -----------------------------------------------------------------------------
create table if not exists public.uploads (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.app_users(id) on delete cascade,
  session_id  uuid references public.sessions(id) on delete set null,
  object_path text not null,                   -- path in the Storage bucket
  public_url  text not null,
  mime_type   text,
  created_at  timestamptz not null default now()
);

create index if not exists uploads_user_id_created_at_idx
  on public.uploads(user_id, created_at desc);

-- -----------------------------------------------------------------------------
-- RLS: disabled because the server uses the service role key.
-- (These tables are never queried with the anon key in this app.)
-- -----------------------------------------------------------------------------
alter table public.app_users disable row level security;
alter table public.sessions  disable row level security;
alter table public.uploads   disable row level security;

-- -----------------------------------------------------------------------------
-- Storage bucket: "uploads" (must be PUBLIC so getPublicUrl() links work)
-- -----------------------------------------------------------------------------
-- The bucket name must match the SUPABASE_BUCKET env var (default "uploads").
insert into storage.buckets (id, name, public)
values ('uploads', 'uploads', true)
on conflict (id) do update set public = true;
